/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-122527-g4561fc5e48-20260122"
#endif /* AVUTIL_FFVERSION_H */
